###GET test
GET http://localhost:3000/

###Insert manager
POST http://localhost:3000/add_manager
Content-Type: application/json

{
    "manager_id":"26f0ab44-d1f5-492a-b1f2-7adac3b3d2e9",
    "is_active": true
}

###create-user
POST http://localhost:3000/create_user
Content-Type: application/json

{
    "full_name": "Robert",
    "mob_num": "+911234587989",
    "pan_num": "ACHRE4321Z",
    "manager_id": "26f0ab44-d1f5-492a-b1f2-7adac3b3d2e9"
}
###
GET http://localhost:3000/users

###
POST http://localhost:3000/get_users
Content-Type: application/json

{
    
}